[package]
name = "stackbloatless"
version = "0.1.0-alpha.1"
authors = ["zefr0x"]
edition = "2021"
description = "A clean and effective interface for stackexchange sites"
readme = "README.md"
homepage = "https://github.com/zefr0x/stackbloatless"
repository = "https://github.com/zefr0x/stackbloatless"
license = "GPL-3.0"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true

[dependencies]
relm4 = { version = "0.7.0-alpha.1", features = ["libadwaita", "macros"] }
reqwest = { version = "0.11.20", features = ["json", "gzip"] }
serde = { version = "1.0.188", features = ["derive"] }
serde_json = { version = "1.0.106" }
markdown = "1.0.0-alpha.13"
shadow-rs = "0.23.0"

[build-dependencies]
shadow-rs = "0.23.0"

[dependencies.adw]
package = "libadwaita"
version = "0.5.2"
features = ["v1_3"]

[dependencies.relm4-icons]
package = "relm4-icons"
version = "0.7.0-alpha.2"
features = [
    "menu-large",
    "loupe",
    "dock-right",
    "library",
    "history-undo",
    "earth"
    ]
