[package]
name = "stackbloatless"
version = "0.1.0-alpha.0"
authors = ["zer0-x"]
edition = "2021"
description = "A clean and effective interface for stackexchange sites"
readme = "README.md"
homepage = "https://github.com/zer0-x/stackbloatless"
repository = "https://github.com/zer0-x/stackbloatless"
license = "GPL-3.0"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
strip = true

[dependencies]
relm4 = { version = "0.6.0", features = ["libadwaita", "macros"] }
reqwest = { version = "0.11.18", features = ["json", "gzip"] }
serde = { version = "1.0.163", features = ["derive"] }
serde_json = { version = "1.0.96" }
markdown = "1.0.0-alpha.10"
shadow-rs = "0.23.0"

[build-dependencies]
shadow-rs = "0.23.0"

[dependencies.adw]
package = "libadwaita"
version = "0.4.1"
features = ["v1_3"]

[dependencies.relm4-icons]
package = "relm4-icons"
version = "0.6.0"
features = [
    "menu-large",
    "loupe",
    ]
