# This Github workflow will create a new release when a tag is pushed,
# then it will build the binary and it will add it to the release assets
# in a tar.gz archive along with other components.
#
# Reference:
#   https://github.com/BurntSushi/ripgrep/blob/master/.github/workflows/release.yml
#   https://github.com/rhino-linux/rhino-setup/blob/master/.github/workflows/package.yml

name: release
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  create-release:
    name: create-release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.release.outputs.upload_url }}
      version: ${{ github.ref_name }}
    steps:
      - name: Create Github Release
        id: release
        uses: softprops/action-gh-release@v1
        with:
          body: "For details read the `CHANGELOG.md` file."
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}

  build-release:
    name: build-release
    needs: ["create-release"]
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    env:
      TARGET_DIR: ./target
      # Emit backtraces on panics.
      RUST_BACKTRACE: 1
    strategy:
      matrix:
        build: [linux]
        include:
          - build: linux
            os: ubuntu-latest
            container: fedora:40
            rust: stable
            target: x86_64-unknown-linux-gnu
    steps:
      - name: Install System Deps
        shell: bash
        run: |
          sudo dnf upgrade --refresh -y
          sudo dnf install -y gcc gcc-c++ clang python3 make cmake meson git gh kernel-devel gtk4-devel libadwaita-devel appstream-devel desktop-file-utils

      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup
        run: meson setup builddir

      - name: Build
        run: meson install -C builddir --destdir "builds/${{ matrix.target }}"

      - name: Create Archive
        shell: bash
        run: |
          archive="stackbloatless-${{ needs.create-release.outputs.version }}-${{ matrix.target }}.tar.gz"

          tar -C "builddir/builds/" --create "${{ matrix.target }}/" --gzip --file "$archive"
          echo "ASSET=$archive" >> $GITHUB_ENV

      - name: Upload Release Archive
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ${{ env.ASSET }}
          asset_name: ${{ env.ASSET }}
          asset_content_type: application/octet-stream
